import { NextResponse } from "next/server";
import { prisma } from "@/lib/prisma";
import { logAudit } from "@/lib/audit";

export const dynamic = "force-dynamic";

export async function POST(req: Request) {
  try {
    const body = await req.json();
    const { plannedOrders } = body;

    if (!Array.isArray(plannedOrders) || plannedOrders.length === 0) {
      return NextResponse.json(
        { error: "No planned orders provided" },
        { status: 400 },
      );
    }

    const createdRequisitions = [];

    for (let i = 0; i < plannedOrders.length; i++) {
      const order = plannedOrders[i];
      const reqNumber = `REQ-${new Date().getFullYear()}-${Math.floor(1000 + Math.random() * 9000)}-${i + 1}`;

      const requisition = await prisma.purchaseRequisition.create({
        data: {
          reqNumber,
          title: `MRP Auto-Requisition: ${order.itemName} (${order.itemCode})`,
          description: `Generated by MRP Engine for ${order.parentDemandRef}. Reason: ${order.reason}`,
          itemName: order.itemName,
          qty: order.suggestedQty,
          unit: "units",
          estimatedCost: order.estimatedCost,
          urgency: order.suggestedQty > 50 ? "CRITICAL" : "NORMAL",
          status: "OPEN",
        },
      });

      createdRequisitions.push(requisition);
    }

    await logAudit({
      actor: "system",
      action: "MRP_REQUISITIONS_GENERATED",
      entityType: "PurchaseRequisition",
      entityId: `batch-${Date.now()}`,
      details: `Generated ${createdRequisitions.length} purchase requisitions from MRP run.`,
    });

    return NextResponse.json({
      success: true,
      count: createdRequisitions.length,
      requisitions: createdRequisitions,
    });
  } catch (error: any) {
    console.error("Failed to generate requisitions from MRP:", error);
    return NextResponse.json(
      { error: error.message || "Failed to generate requisitions" },
      { status: 500 },
    );
  }
}
