import { NextResponse } from "next/server";
import { prisma } from "@/lib/prisma";
import { logAuditTx } from "@/lib/audit";
import { headers } from "next/headers";
import { getUserFromHeaders, canAny } from "@/lib/permissions";

export const dynamic = "force-dynamic";

export async function POST(req: Request) {
  try {
    const headersList = await headers();
    const user = getUserFromHeaders(headersList);
    if (!user.isOwner && !canAny(user, ["supply.edit", "ops.edit", "system.edit"])) {
      return NextResponse.json({ error: "Forbidden" }, { status: 403 });
    }

    const body = (await req.json()) as Record<string, unknown>;
    if (typeof body !== "object" || body === null || Array.isArray(body)) {
      return NextResponse.json({ error: "Invalid request body" }, { status: 400 });
    }
    const plannedOrders = body.plannedOrders;

    if (!Array.isArray(plannedOrders) || plannedOrders.length === 0) {
      return NextResponse.json(
        { error: "No planned orders provided" },
        { status: 400 },
      );
    }

    // Bound batch size to prevent runaway allocations
    const boundedOrders = plannedOrders.slice(0, 500);
    const actor = user.name || user.id || "MRP Planner";
    const batchId = `batch-${Date.now()}`;

    const createdRequisitions = await prisma.$transaction(async (tx) => {
      const results = [];
      const currentYear = new Date().getFullYear();

      for (let i = 0; i < boundedOrders.length; i++) {
        const order = boundedOrders[i];
        const reqNumber = `REQ-${currentYear}-${Math.floor(1000 + Math.random() * 9000)}-${i + 1}`;
        const itemName = String(order?.itemName || "Raw Material").slice(0, 100);
        const itemCode = String(order?.itemCode || "ITEM").slice(0, 50);
        const suggestedQty = Math.max(1, Number(order?.suggestedQty) || 1);
        const estimatedCost = Math.max(0, Number(order?.estimatedCost) || 0);

        const requisition = await tx.purchaseRequisition.create({
          data: {
            reqNumber,
            title: `MRP Auto-Requisition: ${itemName} (${itemCode})`,
            description: `Generated by MRP Engine for ${String(order?.parentDemandRef || "Planned Demand").slice(0, 100)}. Reason: ${String(order?.reason || "Material replenishment").slice(0, 150)}`,
            itemName,
            qty: suggestedQty,
            unit: "units",
            estimatedCost,
            urgency: suggestedQty > 50 ? "CRITICAL" : "NORMAL",
            status: "OPEN",
          },
        });

        results.push(requisition);
      }

      await logAuditTx(tx, {
        actor,
        action: "MRP_REQUISITIONS_GENERATED",
        entityType: "PurchaseRequisition",
        entityId: batchId,
        details: `Generated ${results.length} purchase requisitions from MRP run.`,
      });

      return results;
    });

    return NextResponse.json({
      success: true,
      count: createdRequisitions.length,
      requisitions: createdRequisitions,
    });
  } catch (error: unknown) {
    console.error("Failed to generate requisitions from MRP:", error);
    return NextResponse.json(
      { error: "Internal Server Error" },
      { status: 500 },
    );
  }
}
