import { NextResponse } from "next/server";
import { prisma } from "@/lib/prisma";
import { logAudit } from "@/lib/audit";

export async function POST(request: Request) {
  try {
    const body = await request.json();
    // @ts-ignore - body is any from req.json()
    if (typeof body !== "object" || body === null || Array.isArray(body)) {
      return NextResponse.json({ error: "Invalid request body" }, { status: 400 });
    }
    const { machineId, state, cycleCount } = body;

    if (!machineId || !state) {
      return NextResponse.json(
        { error: "machineId and state are required" },
        { status: 400 },
      );
    }

    const machine = await prisma.machine.findUnique({
      where: { id: machineId },
      include: {
        downtimeLogs: {
          where: { endTime: null }, // find open downtime log
        },
      },
    });

    if (!machine) {
      return NextResponse.json({ error: "Machine not found" }, { status: 404 });
    }

    // Always create telemetry log and update machine state
    await prisma.$transaction(async (tx) => {
      // 1. Update machine
      await tx.machine.update({
        where: { id: machineId },
        data: {
          currentState: state,
          lastPingAt: new Date(),
        },
      });

      // 2. Create telemetry log
      await tx.telemetryLog.create({
        data: {
          machineId,
          state,
          cycleCount,
        },
      });

      // 3. Handle Auto-Downtime Logic
      const openLog = machine.downtimeLogs[0];
      const now = new Date();

      if ((state === "FAULT" || state === "IDLE") && !openLog) {
        // Need to create a new downtime log
        // First find or create the IoT reason
        let reason = await tx.downtimeReason.findFirst({
          where: { code: "IOT_AUTO" },
        });

        if (!reason) {
          reason = await tx.downtimeReason.create({
            data: {
              code: "IOT_AUTO",
              description: "IoT Auto-Logged / Machine Fault",
              category: "MECHANICAL", // Defaulting to mechanical
            },
          });
        }

        await tx.downtimeLog.create({
          data: {
            machineId,
            reasonId: reason.id,
            startTime: now,
            notes: `Auto-generated by IoT ping (${state})`,
          },
        });
      } else if (state === "RUNNING" && openLog) {
        // Need to close the open downtime log
        const durationMinutes =
          (now.getTime() - openLog.startTime.getTime()) / (1000 * 60);

        await tx.downtimeLog.update({
          where: { id: openLog.id },
          data: {
            endTime: now,
            durationMinutes,
            status: "FINALIZED",
          },
        });
      }
    });

    await logAudit({
      actor: "system",
      action: "PING_RECEIVED",
      entityType: "Machine",
      entityId: machineId,
      details: `state=${state} · cycles=${cycleCount ?? "n/a"}`,
    });

    return NextResponse.json({ success: true });
  } catch (error) {
    console.error("Error processing IoT ping:", error);
    return NextResponse.json(
      { error: "Internal Server Error" },
      { status: 500 },
    );
  }
}
